Add linux-cachyos-rt
CachyOS/linux-cachyos pull request #127
Opened 2023-06-28 19:52 UTC by ventureoo

Adds a new kernel with RT patches. Wasn't tested very thoroughly, but at least it boots normally.
Notice that the config of this kernel can be synchronized just like all other kernels (linux-rt config is not needed).
 
Compared to other kernels:

- Has 1000Hz by default (matches linux-rt in arch)
- Has Idle ticks by default (matches linux-rt in arch)
- With this kernel, changing the `_preempt` parameter has no effect.
- No other schedulers except CFS are supported (and never will be, but it might make sense to experiment with BORE)

~~god, give me the strength to support these patches~~

2023-06-28 20:02 UTC, ptr1337 commented
I don't know if we really should merge this.
Actually this requires a additional maintenance and I don't really have the spare time for this anymore.
If anyone is willing to do this - its welcome, but we should keep it proper maintained.

Besides that it seems fine for me. Im not sure if we should include this into LTS Kernels (hardned and lts one)

2023-06-28 20:08 UTC, ventureoo commented
> I don't know if we really should merge this. Actually this requires a additional maintenance and I don't really have the spare time for this anymore. If anyone is willing to do this - its welcome, but we should keep it proper maintained.
> 
> Besides that it seems fine for me. Im not sure if we should include this into LTS Kernels (hardned and lts one)

If you want, I can be a maintainer.

As for the additional maintenance, I can say that it all depends on how quickly those or other patches will hit the upstream -> more need to rebase. Basically, apart from constantly updating the patch, nothing is needed, as I managed to avoid enabling CONFIG_EXPERT, otherwise it would have been a real headache.

2023-06-28 20:14 UTC, ventureoo commented
\> Besides that it seems fine for me. Im not sure if we should include this into LTS Kernels (hardned and lts one)

I just added a description of it in them to make it easier to make changes together for all kernels. But if you don't need it, I can remove it.

2023-06-30 11:40 UTC, ventureoo commented
@sirlucjan @ptr1337 The last commit https://github.com/CachyOS/linux-cachyos/pull/127/commits/a92e68f9f74b40a716eb0a59ac48a848942d1fe4 adds a warning about the incompatibility of the RT kernel with ZFS. We could also add a lincense bypass, but that will probably never be the right solution.

2023-06-30 11:52 UTC, sirlucjan commented
It is only right not to add ZFS support to linux-cachyos-rt. We cannot change the ZFS licence or get around this in any other way.

2023-06-30 12:11 UTC, ptr1337 commented
I dont know if we should force to disable zfs on the RT kernel.
If ZFS users want to do the "workaround" then they can do it with inserting a simple line. The problem is that we are not allowed to package it and provide it in a repo - to a user it does not care at all for private usage.

2023-06-30 12:12 UTC, ptr1337 requested changes

2023-06-30 12:12 UTC, ptr1337 commented on linux-bore/PKGBUILD
> +if [ -n "$_build_zfs" ] && [ "$_cpusched" != "rt" ]; then
This additon can be removed from my side - it makes more easy to RT users with zfs to compile the kernel on their own

2023-06-30 12:12 UTC, ptr1337 commented on linux-bore/PKGBUILD
> +    if [ -n "$_build_zfs" ] && [ "$_cpusched" != "rt"]; then
Same and also at all others. Besides that im good with.

I just modify the script for RT at compile it on its own.

2023-06-30 12:23 UTC, ventureoo commented
> I dont know if we should force to disable zfs on the RT kernel. If ZFS users want to do the "workaround" then they can do it with inserting a simple line. The problem is that we are not allowed to package it and provide it in a repo - to a user it does not care at all for private usage.

This may be true, but are there so many ZFS users who want to use the RT kernel? I don't think using workarounds is a good idea. But if you want, I will of course remove some of the changes.

2023-06-30 12:28 UTC, ventureoo commented on linux-bore/PKGBUILD
> +if [ -n "$_build_zfs" ] && [ "$_cpusched" != "rt" ]; then
Done by https://github.com/CachyOS/linux-cachyos/pull/127/commits/d3788abbffc6fecd45dc5baec264550c814d1093

2023-06-30 12:28 UTC, ventureoo commented on linux-bore/PKGBUILD
> +    if [ -n "$_build_zfs" ] && [ "$_cpusched" != "rt"]; then
Done by https://github.com/CachyOS/linux-cachyos/pull/127/commits/d3788abbffc6fecd45dc5baec264550c814d1093

2023-06-30 12:40 UTC, ptr1337 approved these changes

2023-06-30 12:41 UTC, sirlucjan approved these changes

2023-06-30 12:41 UTC, merged